`define MODULE_NAME FFT_Top
`define FIXED
`define FFT8
`define POINTS 8
`define POINTS_LOG 3
`define TARGET_DEVICE_GW1A2A
`define MODE_FORWARD
`define OUTPUT_NATURAL
`define SCALING_RS111
`define INPUT_DATA_WIDTH 8
`define INPUT_DATA_WIDTH_LOG 3
`define TWIDDLE_FACTOR_WIDTH 8
`define TWIDDLE_FACTOR_WIDTH_LOG 3
`define OUTPUT_DATA_WIDTH 8
`define OUTPUT_DATA_WIDTH_LOG 3
`define REDUCTION_TRUNCATION
`define DSP_BLOCK_BASED
`define EBR_MEMORY
`define TDF_EBR_MEMORY
