-d C:\GitHub\TangNano-9K-example\hdmi\impl\gwsynthesis\hdmi.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\GitHub\TangNano-9K-example\hdmi\src\hdmi.cst
-cfg C:\GitHub\TangNano-9K-example\hdmi\impl\pnr\device.cfg
-sdc C:\GitHub\TangNano-9K-example\hdmi\src\hdmi.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
